### ISSUE TITLE
Issue when signing up & requesting to be a validator

### ISSUE THREAD

**Issue by rethore** [FractalFlows/Competipedia#9]
When one clicks on "request to be a validator" during the signing up process, the validator modal won't close until one has validated the email. However, there is no visible hint about what is going on.

Two solutions:
- Print out the hint that the user needs to validate his email
- Send the request despite the fact that the user hasn't yet validated his email.

**Comment by guilhermedecampo** [comment]
I removed the validation for email when you tick the checkbox for being a validator on signup
